version: '3'
networks:
  ms-go-network:
    driver: bridge
services:
  db-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    restart: on-failure
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - ms-go-network
  app:
    container_name: full_app
    build: .
    ports:
      - 8080:8080
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - db-postgres
    networks:
      - ms-go-network
volumes:
  api:
  database_postgres: